SET local check_function_bodies = off;

CREATE TABLE "public"."admins" (
  "id" uuid NOT NULL,
  CONSTRAINT "admins_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."admins"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."announcement_comments" (
  "id"              uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "announcement_id" uuid                     NOT NULL,
  "author_id"       uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "content"         text                     NOT NULL DEFAULT ''::text,
  "created_at"      timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "announcement_comments_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."announcement_comments"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."announcement_reactions" (
  "announcement_id" uuid NOT NULL,
  "user_id"         uuid NOT NULL,
  CONSTRAINT "announcement_reactions_pkey" PRIMARY KEY (announcement_id, user_id)
);

ALTER TABLE "public"."announcement_reactions"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."announcements" (
  "id"         uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "author_id"  uuid,
  "content"    text                     NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "media"      text,
  "title"      text                     NOT NULL,
  CONSTRAINT "announcements_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."announcements"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."courses" (
  "id"   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" text   NOT NULL,
  CONSTRAINT "courses_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."courses"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."events" (
  "event_id"          bigint            GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "event_name"        text              NOT NULL,
  "event_date"        date              NOT NULL,
  "event_description" character varying NOT NULL,
  CONSTRAINT "events_pkey" PRIMARY KEY (event_id)
);

ALTER TABLE "public"."events"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."faculty" (
  "id"     uuid,
  "course" text NOT NULL
);

ALTER TABLE "public"."faculty"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."students" (
  "id"         uuid   NOT NULL,
  "student_id" text   NOT NULL,
  "year_level" bigint NOT NULL,
  "course"     bigint NOT NULL,
  "birthdate"  date,
  CONSTRAINT "students_id_key" UNIQUE (id),
  CONSTRAINT "students_pkey" PRIMARY KEY (student_id)
);

ALTER TABLE "public"."students"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."user_requests" (
  "user_id"      uuid                     NOT NULL,
  "reject_date"  timestamp with time zone,
  "submitted_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
  CONSTRAINT "user_requests_pkey" PRIMARY KEY (user_id)
);

ALTER TABLE "public"."user_requests"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."users" (
  "id"            uuid                     NOT NULL,
  "last_name"     text,
  "first_name"    text,
  "created_at"    timestamp with time zone NOT NULL DEFAULT now(),
  "avatar_path"   text,
  "email_address" text                     NOT NULL,
  CONSTRAINT "users_email_address_key" UNIQUE (email_address),
  CONSTRAINT "users_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."users"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."yearlevels" (
  "id"   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" text   NOT NULL,
  CONSTRAINT "yearlevels_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."yearlevels"
  ENABLE ROW LEVEL SECURITY;

CREATE TYPE "public"."announcement_tags" AS ENUM (
  'FINANCE',
  'TRANSPARENCY',
  'EVENT',
  'ACADEMIC',
  'GENERAL'
);

ALTER TABLE "public"."announcements"
  ADD COLUMN "tag" public.announcement_tags NOT NULL;

CREATE TYPE "public"."user_status" AS ENUM (
  'pending',
  'accept',
  'reject'
);

ALTER TABLE "public"."user_requests"
  ADD COLUMN "request_status" public.user_status NOT NULL;

CREATE OR REPLACE FUNCTION public.is_admin()
  RETURNS boolean
  LANGUAGE sql
  STABLE
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
  select exists (
    select 1 from public.admins where id = (select auth.uid())
  );
$function$;

CREATE OR REPLACE FUNCTION public.on_user_register()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$DECLARE
  user_role text;
  f_name text;
  l_name text;
  email text;
BEGIN

  IF (NEW.raw_app_meta_data ->> 'provider') = 'google' THEN
    RAISE EXCEPTION 'Access denied: Self-registration via Google is not allowed. Your email must be added by an administrator first.';
  END IF;
  -- Extract name safely from either email signup or Google OAuth metadata
  f_name := COALESCE(
    NEW.raw_user_meta_data ->> 'first_name',
    NEW.raw_user_meta_data ->> 'given_name',
    split_part(NEW.raw_user_meta_data ->> 'full_name', ' ', 1),
    ''
  );
  
  l_name := COALESCE(
    NEW.raw_user_meta_data ->> 'last_name',
    NEW.raw_user_meta_data ->> 'family_name',
    substr(NEW.raw_user_meta_data ->> 'full_name', length(split_part(NEW.raw_user_meta_data ->> 'full_name', ' ', 1)) + 2),
    ''
  );

  email := COALESCE(
    NEW.raw_user_meta_data ->> 'email_address',
    NEW.raw_user_meta_data ->> 'email'
  );

  -- 1. Create base record in public.users
  INSERT INTO public.users (id, first_name, last_name)
  VALUES (NEW.id, f_name, l_name);

  user_role := COALESCE(NEW.raw_user_meta_data ->> 'role', '');

  -- 2. Only insert into students if student_id is explicitly provided
  IF (user_role = 'student' OR (NEW.raw_user_meta_data ->> 'student_id') IS NOT NULL) 
     AND (NEW.raw_user_meta_data ->> 'student_id') <> '' THEN
    INSERT INTO public.students (
      id, 
      student_id, 
      year_level, 
      course
    )
    VALUES (
      NEW.id,
      NEW.raw_user_meta_data ->> 'student_id',
      NULLIF(NEW.raw_user_meta_data ->> 'year_level', '')::bigint,
      NULLIF(NEW.raw_user_meta_data ->> 'course_id', '')::bigint
    );
  END IF;

  RETURN NEW;
END;$function$;

ALTER TABLE "public"."announcement_comments"
  ADD CONSTRAINT "announcement_comments_announcement_id_fkey" FOREIGN KEY (announcement_id) REFERENCES public.announcements(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."announcement_reactions"
  ADD CONSTRAINT "announcement_reactions_announcement_id_fkey" FOREIGN KEY (announcement_id) REFERENCES public.announcements(id);

ALTER TABLE "public"."students"
  ADD CONSTRAINT "students_course_fkey" FOREIGN KEY (course) REFERENCES public.courses(id);

ALTER TABLE "public"."users"
  ADD CONSTRAINT "users_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."admins"
  ADD CONSTRAINT "admins_id_fkey" FOREIGN KEY (id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."announcement_comments"
  ADD CONSTRAINT "announcement_comments_author_id_fkey" FOREIGN KEY (author_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."announcement_reactions"
  ADD CONSTRAINT "announcement_reactions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE "public"."announcements"
  ADD CONSTRAINT "announcements_author_id_fkey" FOREIGN KEY (author_id) REFERENCES public.users(id);

ALTER TABLE "public"."faculty"
  ADD CONSTRAINT "faculty_id_fkey" FOREIGN KEY (id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."students"
  ADD CONSTRAINT "students_id_fkey" FOREIGN KEY (id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."user_requests"
  ADD CONSTRAINT "user_requests_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE "public"."students"
  ADD CONSTRAINT "students_year_level_fkey" FOREIGN KEY (year_level) REFERENCES public.yearlevels(id);

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.on_user_register();

CREATE POLICY "Admins can see their own status" ON "public"."admins"
  FOR SELECT
  TO "authenticated"
  USING ((auth.uid() = id));

CREATE POLICY "Authenticated can edit their own comments" ON "public"."announcement_comments"
  FOR UPDATE
  TO "authenticated"
  USING ((author_id = ( SELECT auth.uid() AS uid)))
  WITH CHECK ((author_id = ( SELECT auth.uid() AS uid)));

CREATE POLICY "Authenticated can read all comments" ON "public"."announcement_comments"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "Authenticated can write their own comments" ON "public"."announcement_comments"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((author_id = ( SELECT auth.uid() AS uid)));

CREATE POLICY "Authors and admins can delete comments" ON "public"."announcement_comments"
  FOR DELETE
  TO "authenticated"
  USING (((author_id = ( SELECT auth.uid() AS uid)) OR ( SELECT public.is_admin() AS is_admin)));

CREATE POLICY "Enable delete for users based on user_id" ON "public"."announcement_reactions"
  FOR DELETE
  TO PUBLIC
  USING ((( SELECT auth.uid() AS uid) = user_id));

CREATE POLICY "Enable insert for users based on user_id" ON "public"."announcement_reactions"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));

CREATE POLICY "Enable read access for all users" ON "public"."announcement_reactions"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "Admins can DELETE announcements" ON "public"."announcements"
  FOR DELETE
  TO "authenticated"
  USING (( SELECT public.is_admin() AS is_admin));

CREATE POLICY "Admins can UPDATE announcements contents" ON "public"."announcements"
  FOR UPDATE
  TO "authenticated"
  USING (( SELECT public.is_admin() AS is_admin))
  WITH CHECK ((( SELECT public.is_admin() AS is_admin) AND (author_id = ( SELECT auth.uid() AS uid))));

CREATE POLICY "Admins can WRITE announcements" ON "public"."announcements"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((( SELECT public.is_admin() AS is_admin) AND (author_id = ( SELECT auth.uid() AS uid))));

CREATE POLICY "Enable read access for all users" ON "public"."announcements"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Anyone can read course data" ON "public"."courses"
  FOR SELECT
  TO "anon", "authenticated"
  USING (true);

CREATE POLICY "allow read for all user" ON "public"."students"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."user_requests"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Authenticated users can read profiles" ON "public"."users"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "insert users" ON "public"."users"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (true);

CREATE POLICY "users update their own row" ON "public"."users"
  FOR UPDATE
  TO "authenticated"
  USING ((auth.uid() = id))
  WITH CHECK ((auth.uid() = id));

CREATE POLICY "Anyone can view yearlevels data" ON "public"."yearlevels"
  FOR SELECT
  TO "anon", "authenticated"
  USING (true);

CREATE POLICY "avatars are public" ON "storage"."objects"
  FOR SELECT
  TO PUBLIC
  USING ((bucket_id = 'avatars'::text));

CREATE POLICY "users delete their own avatar" ON "storage"."objects"
  FOR DELETE
  TO PUBLIC
  USING (((bucket_id = 'avatars'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));

CREATE POLICY "users update their own avatar" ON "storage"."objects"
  FOR UPDATE
  TO PUBLIC
  USING (((bucket_id = 'avatars'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));

CREATE POLICY "users upload their own avatar" ON "storage"."objects"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (((bucket_id = 'avatars'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));

GRANT EXECUTE ON FUNCTION "public"."is_admin"() TO PUBLIC, "anon", "authenticated";

REVOKE ALL ON FUNCTION "public"."is_admin"() FROM "postgres";

GRANT EXECUTE ON FUNCTION "public"."is_admin"() TO "postgres";

GRANT EXECUTE ON FUNCTION "public"."is_admin"() TO "service_role";

GRANT EXECUTE ON FUNCTION "public"."on_user_register"() TO PUBLIC, "anon", "authenticated";

REVOKE ALL ON FUNCTION "public"."on_user_register"() FROM "postgres";

GRANT EXECUTE ON FUNCTION "public"."on_user_register"() TO "postgres";

GRANT EXECUTE ON FUNCTION "public"."on_user_register"() TO "service_role";

REVOKE ALL ON SEQUENCE "public"."courses_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."courses_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."courses_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."courses_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."courses_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."courses_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."courses_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."courses_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."events_event_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."events_event_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."events_event_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."events_event_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."events_event_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."events_event_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."events_event_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."events_event_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."yearlevels_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."yearlevels_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."yearlevels_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."yearlevels_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."yearlevels_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."yearlevels_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."yearlevels_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."yearlevels_id_seq" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."admins" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."admins" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."admins" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."admins" TO "service_role";

REVOKE ALL ON TABLE "public"."announcement_comments" FROM "anon";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."announcement_comments" TO "anon";

REVOKE ALL ON TABLE "public"."announcement_comments" FROM "authenticated";

REVOKE ALL ("content") ON TABLE "public"."announcement_comments" FROM "authenticated";

GRANT UPDATE ("content") ON TABLE "public"."announcement_comments" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."announcement_comments" TO "authenticated";

REVOKE ALL ON TABLE "public"."announcement_comments" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."announcement_comments" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."announcement_comments" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."announcement_reactions" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."announcement_reactions" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."announcement_reactions" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."announcement_reactions" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."announcements" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."announcements" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."announcements" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."announcements" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."courses" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."courses" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."courses" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."courses" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."events" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."events" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."events" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."events" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."faculty" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."faculty" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."faculty" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."faculty" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."students" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."students" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."students" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."students" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_requests" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."user_requests" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_requests" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_requests" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."users" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."users" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."users" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."users" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."yearlevels" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."yearlevels" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."yearlevels" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."yearlevels" TO "service_role";

